[package]
name = "turnip-calc"
version = "1.1.0"
description = "Turnip Pattern Calculator for Animal Crossing: New Leaf and New Horizons."
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
